# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lr2_api', '0002_auto_20161115_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelcompany',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
