# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr2_api', '0003_travelcompany_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default='ewfuywegfuew', max_length=100, verbose_name='OAuth2 Code'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='routeuser',
            unique_together=set([('route', 'user')]),
        ),
    ]
