# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lr2_api', '0004_auto_20161122_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('client_id', models.CharField(max_length=100, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=255, verbose_name='Client Secret')),
                ('redirect_uri', models.CharField(max_length=100, verbose_name='Redirect URI')),
            ],
            options={
                'verbose_name_plural': 'OAuth2 Apps',
                'verbose_name': 'OAuth2 App',
            },
        ),
        migrations.CreateModel(
            name='OAuthCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, verbose_name='Code')),
                ('expires', models.DateTimeField(verbose_name='Истекает в')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lr2_api.Application')),
            ],
            options={
                'verbose_name_plural': 'OAuth2 Codes',
                'verbose_name': 'OAuth2 Code',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expires_in',
        ),
        migrations.AddField(
            model_name='oauthcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
